'use client';

import { Controller, useFormContext } from 'react-hook-form';
import { Grid, Box, TextField, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';
import moment from 'moment-jalaali';
import { useEffect } from 'react';

// Services
import { useGetPersonnels } from 'src/services/personnels/personnels.servise';
import { useGetVisitReason } from 'src/services/visitReason/visitReason.service';
import { useGetReservedCards } from 'src/services/reservedCards/reservedCards.service';
import { useGetAccessGroups } from 'src/services/access-groups/access-groups.service';
import { useGetDoors } from 'src/services/doors/doors.service';
import { useGetUnits } from 'src/services/units/units.service';
import { useTranslate } from 'src/locales';
import { Field } from 'src/components/hook-form';

export function AppointmentSection({ scheduleTypeData, isEditing }) {
  const inputSx = {
    '& .MuiInputBase-root': { height: 38, fontSize: 13 },
    '& .MuiInputBase-input': { padding: '6px 10px' },
    '& .MuiInputLabel-root': { fontSize: 12, top: '-3px' },
    '& .MuiOutlinedInput-notchedOutline': { borderRadius: 1 },
  };

  const { t: t_appointment } = useTranslate('appointment');
  const { control, watch, setValue } = useFormContext();

  const hostUnitId = watch('hostUnitId');
  const cardType = watch('cardType');
  const WatchDoor = watch('entryDoor');
  const entryDeviceIdsWatch = watch('entryDeviceIds');

  const {
    data: units,
    refetch: refetchUnits,
    isFetching: isUnitsFetching,
  } = useGetUnits({}, false);

  const {
    data: personnels,
    refetch: refetchPersonnels,
    isFetching: isPersonnelsFetching,
  } = useGetPersonnels({ unitId: hostUnitId }, true);

  const personnelOptions = personnels?.items?.map((item) => ({
    id: item.id,
    label: `${item?.firstName} ${item?.lastName}`,
  }));

  const {
    data: visitReasons,
    refetch: refetchVisitReasons,
    isFetching: isVisitReasonsFetching,
  } = useGetVisitReason({}, true);

  const {
    data: cards,
    refetch: refetchCards,
    isFetching: isCardsFetching,
  } = useGetReservedCards({}, true);

  const {
    data: accessGroups,
    refetch: refetchAccessGroups,
    isFetching: isAccessGroupsFetching,
  } = useGetAccessGroups({}, false);

  const { data: doorsData, refetch: refetchDoorsData, isFetching: isDoorsFetching } = useGetDoors();

  const hostIdWatch = watch('hostId');

  useEffect(() => {
    if (hostUnitId) {
      setValue('hostId');
    }
  }, [hostUnitId, setValue]);

  useEffect(() => {
    if (cardType === 'AutoGenerated') {
      setValue('visitorCardId');
    }
  }, [cardType, setValue]);

  return (
    <Grid container>
      <Grid size={{ xs: 12 }}>
        <Box display="flex" flexDirection="column">
          <Box
            sx={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 1, minHeight: 64 }}
          >
            <Field.Select
              name="cardType"
              label={t_appointment('formsInputs.cardType.label')}
              data={[
                { id: 'Physical', label: t_appointment('formsInputs.cardType.physical') },
                { id: 'AutoGenerated', label: t_appointment('formsInputs.cardType.autoGenerated') },
                { id: 'WithoutCard', label: t_appointment('formsInputs.cardType.withoutCard') },
              ]}
              valueExp="id"
              displayExp="label"
              sx={inputSx}
              size="small"
            />

            {cardType === 'Physical' && (
              <Field.Select
                name="visitorCardId"
                label={t_appointment('formsInputs.visitorCard')}
                data={cards?.items ?? []}
                valueExp="id"
                displayExp="cardNumber"
                loading={isCardsFetching}
                onOpen={() => {
                  if (!cards?.items?.length) refetchCards();
                }}
                sx={inputSx}
                size="small"
              />
            )}

            <Field.Select
              name="hostUnitId"
              label={t_appointment('formsInputs.hostUnit')}
              data={units?.items ?? []}
              valueExp="id"
              displayExp="name"
              loading={isUnitsFetching}
              onOpen={() => {
                if (!units?.items?.length) refetchUnits();
              }}
              sx={inputSx}
              size="small"
            />

            <Field.Select
              name="hostId"
              label={t_appointment('formsInputs.hostPersonnel')}
              data={personnelOptions || []}
              valueExp="id"
              displayExp="label"
              loading={isPersonnelsFetching}
              onOpen={() => {
                if (!personnelOptions?.length && hostUnitId) refetchPersonnels();
              }}
              sx={inputSx}
              size="small"
            />

            <Field.Select
              name="visitReasonId"
              label={t_appointment('formsInputs.visitReason')}
              data={visitReasons?.items ?? []}
              valueExp="id"
              displayExp="name"
              loading={isVisitReasonsFetching}
              onOpen={() => {
                if (!visitReasons?.items?.length) refetchVisitReasons();
              }}
              sx={inputSx}
              size="small"
            />
          </Box>

          <Box sx={{ display: 'flex', flexDirection: 'column', width: '100%', mb: 1 }}>
            <Typography variant="body1" sx={{ fontWeight: 500 }}>
              اطلاعات بازه ملاقات
            </Typography>
          </Box>

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(6, 1fr)',
              gap: 1,
              minHeight: 64,
            }}
          >
            <Controller
              name="visitDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitDate')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v ? v.toISOString() : null)}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message || '',
                    },
                  }}
                />
              )}
            />

            <Controller
              name="visitStartTime"
              control={control}
              render={({ field, fieldState }) => (
                <TimePicker
                  label={t_appointment('formsInputs.visitStartTime')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v ? v.toISOString() : null)}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message || '',
                    },
                  }}
                />
              )}
            />

            <Controller
              name="visitEndDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitEndDate')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v ? v.toISOString() : null)}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message || '',
                    },
                  }}
                />
              )}
            />

            <Controller
              name="visitEndTime"
              control={control}
              render={({ field, fieldState }) => (
                <TimePicker
                  label={t_appointment('formsInputs.visitEndTime')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v ? v.toISOString() : null)}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message || '',
                    },
                  }}
                />
              )}
            />
          </Box>

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(6, 1fr)',
              gap: 1,
              minHeight: 64,
            }}
          >
            <Field.Select
              name="entryDoor"
              label="درب ورود"
              data={doorsData?.items ?? []}
              valueExp="id"
              displayExp="doorName"
              loading={isDoorsFetching}
              onOpen={() => {
                if (!doorsData?.items?.length) refetchDoorsData();
              }}
              sx={inputSx}
              size="small"
            />

            <Field.Select
              name="entryDeviceIds"
              label="دستگاه ورود"
              data={accessGroups?.items ?? []}
              valueExp="id"
              displayExp="name"
              multiple
              loading={isAccessGroupsFetching}
              onOpen={() => {
                if (!accessGroups?.items?.length) refetchAccessGroups();
              }}
              sx={inputSx}
              size="small"
            />

            <Field.Select
              name="exitDoor"
              label="درب خروج"
              data={doorsData?.items ?? []}
              valueExp="id"
              displayExp="doorName"
              loading={isDoorsFetching}
              onOpen={() => {
                if (!doorsData?.items?.length) refetchDoorsData();
              }}
              sx={inputSx}
              size="small"
            />

            <Field.Select
              name="exitDeviceIds"
              label="دستگاه خروج"
              data={accessGroups?.items ?? []}
              valueExp="id"
              displayExp="name"
              multiple
              loading={isAccessGroupsFetching}
              onOpen={() => {
                if (!accessGroups?.items?.length) refetchAccessGroups();
              }}
              sx={inputSx}
              size="small"
            />
          </Box>

          {/* ===================== ROW 2 ===================== */}
          {!isEditing && cardType === 'WithoutCard' && scheduleTypeData === 'WithoutApproval' && (
            <>
              <Box sx={{ display: 'flex', flexDirection: 'column', width: '100%', mb: 1 }}>
                <Typography variant="body1" sx={{ fontWeight: 500 }}>
                  اطلاعات تردد مهمان
                </Typography>
              </Box>

              <Box
                sx={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(6, 1fr)',
                  gap: 1,
                  minHeight: 64,
                }}
              >
                {/*  Visit Date */}
                <Controller
                  name="visitAccessDate"
                  control={control}
                  render={({ field, fieldState }) => (
                    <DatePicker
                      label="تاریخ شروع تردد"
                      value={field.value ? moment(field.value) : null}
                      onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                      slotProps={{
                        textField: {
                          size: 'small',
                          sx: inputSx,
                          error: !!fieldState.error,
                          helperText: fieldState.error?.message || '',
                        },
                      }}
                    />
                  )}
                />

                {/*  Visit Start Time */}
                <Controller
                  name="visitAccessStartTime"
                  control={control}
                  render={({ field, fieldState }) => (
                    <TimePicker
                      label="ساعت شروع تردد"
                      value={field.value ? moment(field.value) : null}
                      onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                      slotProps={{
                        textField: {
                          size: 'small',
                          sx: inputSx,
                          error: !!fieldState.error,
                          helperText: fieldState.error?.message || '',
                        },
                      }}
                    />
                  )}
                />
                {/*  Visit End Date */}
                <Controller
                  name="visitAccessEndDate"
                  control={control}
                  render={({ field, fieldState }) => (
                    <DatePicker
                      label="تاریخ پایان تردد"
                      value={field.value ? moment(field.value) : null}
                      onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                      slotProps={{
                        textField: {
                          size: 'small',
                          sx: inputSx,
                          error: !!fieldState.error,
                          helperText: fieldState.error?.message || '',
                        },
                      }}
                    />
                  )}
                />

                {/*  Visit End Time */}
                <Controller
                  name="visitAccessEndTime"
                  control={control}
                  render={({ field, fieldState }) => (
                    <TimePicker
                      label="ساعت پایان تردد"
                      value={field.value ? moment(field.value) : null}
                      onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                      slotProps={{
                        textField: {
                          size: 'small',
                          sx: inputSx,
                          error: !!fieldState.error,
                          helperText: fieldState.error?.message || '',
                        },
                      }}
                    />
                  )}
                />
              </Box>
            </>
          )}

          <Box
            sx={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 1, minHeight: 64 }}
          >
            <Controller
              name="note"
              control={control}
              render={({ field, fieldState }) => (
                <TextField
                  multiline
                  rows={3}
                  {...field}
                  label={t_appointment('formsInputs.note')}
                  size="small"
                  sx={inputSx}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || ' '}
                />
              )}
            />
          </Box>
        </Box>
      </Grid>
    </Grid>
  );
}
