'use client';

import { Controller } from 'react-hook-form';
import { Grid, Card, Box, TextField, MenuItem, Autocomplete } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import moment from 'moment-jalaali';
import { useEffect } from 'react';

// Services
import * as personnelsData from 'src/services/personnels/personnels.servise';
import * as visitReasonsData from 'src/services/visitReason/visitReason.service';
import * as reservedCardsData from 'src/services/reservedCards/reservedCards.service';
import * as accessGroupsData from 'src/services/access-groups/access-groups.service';
import { useGetUnitsSelectList } from 'src/services/units/units.service';
import { useTranslate } from 'src/locales';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';
import Button from '@mui/material/Button';

export function AppointmentSection({ control, watch, setValue }) {
  const inputSx = {
    '& .MuiInputBase-root': {
      height: 38,
      fontSize: 13,
    },
    '& .MuiInputBase-input': {
      padding: '6px 10px',
    },
    '& .MuiInputLabel-root': {
      fontSize: 12,
      top: '-3px',
    },
    '& .MuiOutlinedInput-notchedOutline': {
      borderRadius: 1,
    },
  };

  const { t: t_appointment } = useTranslate('appointment');

  const hostUnitId = watch('hostUnitId');
  const cardType = watch('cardType');

  // ----------------------------
  // Lazy hooks
  // ----------------------------

  const {
    data: units,
    refetch: refetchUnits,
    isFetching: isUnitsFetching,
  } = useGetUnitsSelectList({}, false);

  const {
    data: personnels,
    refetch: refetchPersonnels,
    isFetching: isPersonnelsFetching,
  } = personnelsData.useGetPersonnels({}, true);

  const {
    data: visitReasons,
    refetch: refetchVisitReasons,
    isFetching: isVisitReasonsFetching,
  } = visitReasonsData.useGetVisitReason({}, false);

  const {
    data: cards,
    refetch: refetchCards,
    isFetching: isCardsFetching,
  } = reservedCardsData.useGetReservedCards({}, false);

  const {
    data: accessGroups,
    refetch: refetchAccessGroups,
    isFetching: isAccessGroupsFetching,
  } = accessGroupsData.useGetAccessGroups({}, false);

  // ----------------------------
  // Reset dependent fields
  // ----------------------------
  useEffect(() => {
    setValue('hostId', null);
  }, [hostUnitId, setValue]);

  useEffect(() => {
    if (cardType === 'AutoGenerated') setValue('visitorCardId', null);
  }, [cardType, setValue]);

  return (
    <Grid container>
      <Grid size={{ xs: 12}}>
        <Box display="flex" flexDirection="column" gap={2}>
          {/* ---------------- Card Type ---------------- */}

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(6, 1fr)',
              gap: 1,
            }}
          >
            <Controller
              name="cardType"
              control={control}
              render={({ field }) => (
                <TextField
                  {...field}
                  select
                  label={t_appointment('formsInputs.cardType.label')}
                  size="small"
                  sx={inputSx}
                >
                  <MenuItem value="Physical">
                    {t_appointment('formsInputs.cardType.physical')}
                  </MenuItem>
                  <MenuItem value="AutoGenerated">
                    {t_appointment('formsInputs.cardType.autoGenerated')}
                  </MenuItem>
                </TextField>
              )}
            />

            {/* ---------------- Visitor Card ---------------- */}
            {cardType === 'Physical' && (
              <Controller
                name="visitorCardId"
                control={control}
                render={({ field, fieldState }) => (
                  <Autocomplete
                    options={cards?.items ?? []}
                    loading={isCardsFetching}
                    value={cards?.items.find((c) => c.id === field.value) || null}
                    onChange={(_, v) => field.onChange(v?.id ?? '')}
                    getOptionLabel={(o) => o.cardNumber}
                    onOpen={() => {
                      if (!cards?.items?.length) {
                        refetchCards();
                      }
                    }}
                    renderInput={(params) => (
                      <TextField
                        {...params}
                        label={t_appointment('formsInputs.visitorCard')}
                        size="small"
                        sx={inputSx}
                        error={!!fieldState.error}
                        helperText={fieldState.error?.message}
                      />
                    )}
                  />
                )}
              />
            )}

            {/* ---------------- Host Unit ---------------- */}
            <Controller
              name="hostUnitId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={units?.items || []}
                  loading={isUnitsFetching}
                  value={units?.items?.find((u) => u.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(o) => o.name}
                  onOpen={() => {
                    if (!units?.items?.length) {
                      refetchUnits();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.hostUnit')}
                      size="small"
                      sx={inputSx}
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Host Personnels ---------------- */}
            <Controller
              name="hostId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  disabled={!hostUnitId}
                  options={personnels?.items || []}
                  loading={isPersonnelsFetching}
                  value={personnels?.items.find((p) => p.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(o) => `${o.firstName} ${o.lastName}`}
                  isOptionEqualToValue={(option, value) => option.id === value.id}
                  onOpen={() => {
                    if (hostUnitId && !personnels?.items?.length) {
                      refetchPersonnels({ unitId: hostUnitId });
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.hostPersonnel')}
                      size="small"
                      sx={inputSx}
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Visit Reason ---------------- */}
            <Controller
              name="visitReasonId"
              control={control}
              render={({ field, fieldState }) => (
                <TextField
                  {...field}
                  select
                  label={t_appointment('formsInputs.visitReason')}
                  size="small"
                  sx={inputSx}
                  onFocus={() => {
                    if (!visitReasons?.items?.length) {
                      refetchVisitReasons();
                    }
                  }}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                >
                  {isVisitReasonsFetching ? (
                    <MenuItem disabled>در حال بارگذاری...</MenuItem>
                  ) : visitReasons?.items?.length ? (
                    visitReasons.items.map((reason) => (
                      <MenuItem key={reason.id} value={reason.name}>
                        {reason.name}
                      </MenuItem>
                    ))
                  ) : (
                    <MenuItem disabled>موردی وجود ندارد</MenuItem>
                  )}
                </TextField>
              )}
            />

            {/* ---------------- Visit accessGroup ---------------- */}
          </Box>

          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(6, 1fr)',
              gap: 1,
            }}
          >
            <Controller
              name="accessGroupId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={accessGroups?.items || []}
                  loading={isAccessGroupsFetching}
                  value={accessGroups?.items?.find((v) => v.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(option) => option.name}
                  onOpen={() => {
                    if (!accessGroups?.items?.length) {
                      refetchAccessGroups();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.accessGroupId')}
                      size="small"
                      sx={inputSx}
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/*---------------- Visit Start Time ----------------*/}
            <Controller
              name="visitStartTime"
              control={control}
              render={({ field, fieldState }) => (
                <TimePicker
                  label={t_appointment('formsInputs.visitStartTime')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message,
                    },
                  }}
                />
              )}
            />
            {/* ---------------- Visit Date ---------------- */}
            <Controller
              name="visitDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitDate')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message,
                    },
                  }}
                />
              )}
            />

            <Controller
              name="accessGroupId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={accessGroups?.items || []}
                  loading={isAccessGroupsFetching}
                  value={accessGroups?.items?.find((v) => v.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(option) => option.name}
                  onOpen={() => {
                    if (!accessGroups?.items?.length) {
                      refetchAccessGroups();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="درب خروج"
                      size="small"
                      sx={inputSx}
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />
            {/*---------------- Visit End Date ----------------*/}
            <Controller
              name="visitEndDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitEndDate')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message,
                    },
                  }}
                />
              )}
            />

            {/* ---------------- Visit End Time ---------------- */}
            <Controller
              name="visitEndTime"
              control={control}
              render={({ field, fieldState }) => (
                <TimePicker
                  label={t_appointment('formsInputs.visitEndTime')}
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: {
                      size: 'small',
                      sx: inputSx,
                      error: !!fieldState.error,
                      helperText: fieldState.error?.message,
                    },
                  }}
                />
              )}
            />
          </Box>
          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(2, 1fr)',
              gap: 1,
            }}
          >
            <TextField label={t_appointment('formsInputs.note')} multiline size="small" rows={3} />
          </Box>
        </Box>
      </Grid>
    </Grid>
  );
}
