'use client';

import { Controller } from 'react-hook-form';
import { Grid, Card, Box, TextField, MenuItem, Autocomplete } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import moment from 'moment-jalaali';
import { useEffect, useState } from 'react';

// Services
import * as visitorsData from 'src/services/visitor/visitor.service';
import * as personnelsData from 'src/services/personnels/personnels.servise';
import * as visitReasonsData from 'src/services/visitReason/visitReason.service';
import * as reservedCardsData from 'src/services/reservedCards/reservedCards.service';
import * as accessGroupsData from 'src/services/access-groups/access-groups.service';
import { useGetUnitsSelectList } from 'src/services/units/units.service';
import { useTranslate } from 'src/locales';
import { useGetAccessGroups } from 'src/services/access-groups/access-groups.service';

export function AppointmentSection({ control, watch, setValue }) {
  const { t: t_appointment } = useTranslate('appointment');

  const hostUnitId = watch('hostUnitId');
  const cardType = watch('cardType');

  const [searchTerm, setSearchTerm] = useState('');
  // ----------------------------
  // Lazy hooks
  // ----------------------------
  const {
    data: visitors,
    refetch: refetchVisitors,
    isFetching: isVisitorsFetching,
  } = visitorsData.useGetVisitors({ searchTerm }, true);

  const {
    data: units,
    refetch: refetchUnits,
    isFetching: isUnitsFetching,
  } = useGetUnitsSelectList({}, false);

  const {
    data: personnels,
    refetch: refetchPersonnels,
    isFetching: isPersonnelsFetching,
  } = personnelsData.useGetPersonnels(
    // visitUnitId ? { Filters: `unitid|eq|${visitUnitId}` } : {}
    {},
    false
  );

  const {
    data: visitReasons,
    refetch: refetchVisitReasons,
    isFetching: isVisitReasonsFetching,
  } = visitReasonsData.useGetVisitReason({}, false);

  const {
    data: cards,
    refetch: refetchCards,
    isFetching: isCardsFetching,
  } = reservedCardsData.useGetReservedCards({}, false);

  const {
    data: accessGroups,
    refetch: refetchAccessGroups,
    isFetching: isAccessGroupsFetching,
  } = accessGroupsData.useGetAccessGroups({}, false);

  // ----------------------------
  // Reset dependent fields
  // ----------------------------
  useEffect(() => {
    setValue('hostId', null);
  }, [hostUnitId, setValue]);

  useEffect(() => {
    if (cardType === 'AutoGenerated') setValue('visitorCardId', null);
  }, [cardType, setValue]);

  return (
    <Grid container spacing={3} sx={{ p: 3 }}>
      <Grid size={{ xs: 12 }}>
        <Card sx={{ p: 2, width: '100%' }}>
          <Box display="grid" gap={2} gridTemplateColumns={{ xs: '1fr', sm: '1fr 1fr' }}>
            {/* ---------------- Visitor ---------------- */}
            <Controller
              name="visitorId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={visitors?.items || []}
                  loading={isVisitorsFetching}
                  value={visitors?.items?.find((v) => v.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(o) => `${o.firstName} ${o.lastName}`}
                  onOpen={() => {
                    if (!visitors?.items?.length) {
                      refetchVisitors();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.visitor')}
                      placeholder={t_appointment('formsInputs.visitorPlaceholder')}
                      size="small"
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                      onChange={(e) => setSearchTerm(e.target.value)}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Card Type ---------------- */}
            <Controller
              name="cardType"
              control={control}
              render={({ field }) => (
                <TextField
                  {...field}
                  select
                  label={t_appointment('formsInputs.cardType.label')}
                  size="small"
                >
                  <MenuItem value="Physical">
                    {t_appointment('formsInputs.cardType.physical')}
                  </MenuItem>
                  <MenuItem value="AutoGenerated">
                    {t_appointment('formsInputs.cardType.autoGenerated')}
                  </MenuItem>
                </TextField>
              )}
            />

            {/* ---------------- Visitor Card ---------------- */}
            {cardType === 'Physical' && (
              <Controller
                name="visitorCardId"
                control={control}
                render={({ field, fieldState }) => (
                  <Autocomplete
                    options={cards?.items ?? []}
                    loading={isCardsFetching}
                    value={cards?.items.find((c) => c.id === field.value) || null}
                    onChange={(_, v) => field.onChange(v?.id ?? '')}
                    getOptionLabel={(o) => o.cardNumber}
                    onOpen={() => {
                      if (!cards?.items?.length) {
                        refetchCards();
                      }
                    }}
                    renderInput={(params) => (
                      <TextField
                        {...params}
                        label={t_appointment('formsInputs.visitorCard')}
                        size="small"
                        error={!!fieldState.error}
                        helperText={fieldState.error?.message}
                      />
                    )}
                  />
                )}
              />
            )}

            {/* ---------------- Host Unit ---------------- */}
            <Controller
              name="hostUnitId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={units?.items || []}
                  loading={isUnitsFetching}
                  value={units?.items?.find((u) => u.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(o) => o.name}
                  onOpen={() => {
                    if (!units?.items?.length) {
                      refetchUnits();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.hostUnit')}
                      size="small"
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Host Personnels ---------------- */}
            <Controller
              name="hostId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  disabled={!hostUnitId}
                  options={personnels?.items || []}
                  loading={isPersonnelsFetching}
                  value={personnels?.items.find((p) => p.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(o) => `${o.firstName} ${o.lastName}`}
                  isOptionEqualToValue={(option, value) => option.id === value.id}
                  onOpen={() => {
                    if (hostUnitId && !personnels?.items?.length) {
                      refetchPersonnels({ unitId: hostUnitId });
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.hostPersonnel')}
                      size="small"
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Visit Reason ---------------- */}
            <Controller
              name="visitReasonId"
              control={control}
              render={({ field, fieldState }) => (
                <TextField
                  {...field}
                  select
                  label={t_appointment('formsInputs.visitReason')}
                  size="small"
                  onFocus={() => {
                    if (!visitReasons?.items?.length) {
                      refetchVisitReasons();
                    }
                  }}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                >
                  {isVisitReasonsFetching ? (
                    <MenuItem disabled>در حال بارگذاری...</MenuItem>
                  ) : visitReasons?.items?.length ? (
                    visitReasons.items.map((reason) => (
                      <MenuItem key={reason.id} value={reason.id}>
                        {reason.title || reason.name}
                      </MenuItem>
                    ))
                  ) : (
                    <MenuItem disabled>موردی وجود ندارد</MenuItem>
                  )}
                </TextField>
              )}
            />

            <TextField label={t_appointment('formsInputs.note')} size="small" rows={3} />

            {/* ---------------- Visit accessGroup ---------------- */}

            <Controller
              name="accessGroupId"
              control={control}
              render={({ field, fieldState }) => (
                <Autocomplete
                  options={accessGroups?.items || []}
                  loading={isAccessGroupsFetching}
                  value={accessGroups?.items?.find((v) => v.id === field.value) || null}
                  onChange={(_, v) => field.onChange(v?.id ?? null)}
                  getOptionLabel={(option) => option.name ?? ''}
                  onOpen={() => {
                    if (!accessGroups?.items?.length) {
                      refetchAccessGroups();
                    }
                  }}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={t_appointment('formsInputs.accessGroupId')}
                      size="small"
                      error={!!fieldState.error}
                      helperText={fieldState.error?.message}
                    />
                  )}
                />
              )}
            />

            {/* ---------------- Visit Date ---------------- */}
            <Controller
              name="visitDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitDate')}
                  size="small"
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: { error: !!fieldState.error, helperText: fieldState.error?.message },
                  }}
                />
              )}
            />

            {/* ---------------- Visit End Date ---------------- */}
            <Controller
              name="visitEndDate"
              control={control}
              render={({ field, fieldState }) => (
                <DatePicker
                  label={t_appointment('formsInputs.visitEndDate')}
                  size="small"
                  value={field.value ? moment(field.value) : null}
                  onChange={(v) => field.onChange(v?.toISOString() ?? '')}
                  slotProps={{
                    textField: { error: !!fieldState.error, helperText: fieldState.error?.message },
                  }}
                />
              )}
            />
          </Box>
        </Card>
      </Grid>
    </Grid>
  );
}
