import { z } from 'zod';

export const companionSchema = z.object({
  firstName: z.string().nullable().optional(),
  lastName: z.string().nullable().optional(),
  gender: z.enum(['Male', 'Female']).nullable().optional(),
  nationalCode: z.string().nullable().optional(),
  phoneNumber: z.string().nullable().optional(),
});

export const createVisitScheduleSchema = (t) =>
  z
    .object({
      /** TAB 1 – Guest */
      visitorTypeId: z.string().min(1, t.guest('formValidationErrors.visitorType')),
      // visitorTypeValue: z.string(),

      firstName: z.string().min(1, t.guest('formValidationErrors.firstName')),
      lastName: z.string().min(1, t.guest('formValidationErrors.lastName')),
      gender: z.string().min(1, t.guest('formValidationErrors.gender')),
      dateOfBirth: z.string().min(1, t.guest('formValidationErrors.dateOfBirth')),
      mobileNumber: z.string().min(1, t.guest('formValidationErrors.mobileNumber')),

      nationalCode: z.string().optional().nullable(),
      passportNumber: z.string().optional().nullable(),
      inclusiveNumber: z.string().optional().nullable(),

      /** TAB 2 – Appointment */
      // visitorId: z.string().min(1, t.appointment('formValidationErrors.visitorId')),
      cardType: z.enum(['Physical', 'AutoGenerated']),
      visitorCardId: z.string().nullable(),
      hostUnitId: z.string().min(1, t.appointment('formValidationErrors.hostUnitId')),
      hostId: z.string().min(1, t.appointment('formValidationErrors.hostId')),
      visitReasonId: z.string().min(1, t.appointment('formValidationErrors.visitReasonId')),
      accessGroupId: z.number().min(1, t.appointment('formValidationErrors.accessGroupId')),
      visitDate: z.string().min(1, t.appointment('formValidationErrors.visitDate')),
      visitEndDate: z.string().min(1, t.appointment('formValidationErrors.visitEndDate')),

      /** TAB 3 */
      groupId: z.string().nullable().optional(),
      visitorItemIds: z.array(z.string()).nullable().optional(),
      note: z.string().nullable().optional(),

      /** TAB 4 */
      companions: z.array(companionSchema).nullable().optional(),
    })
    //  Foreign / Non-Foreign
    .superRefine((data, ctx) => {
      const isForeigner = data.visitorTypeValue === 'Foreigner';

      if (isForeigner) {
        // فقط اینا مهمن
        if (!data.passportNumber) {
          ctx.addIssue({
            path: ['passportNumber'],
            message: t.guest('formValidationErrors.passportNumber'),
            code: z.ZodIssueCode.custom,
          });
        }

        if (!data.inclusiveNumber) {
          ctx.addIssue({
            path: ['inclusiveNumber'],
            message: t.guest('formValidationErrors.inclusiveNumber'),
            code: z.ZodIssueCode.custom,
          });
        }

        return;
      }

      if (!data.nationalCode) {
        ctx.addIssue({
          path: ['nationalCode'],
          message: t.guest('formValidationErrors.nationalCode'),
          code: z.ZodIssueCode.custom,
        });
      }
    })

    //  refine
    .refine((data) => data.cardType !== 'Physical' || !!data.visitorCardId, {
      path: ['visitorCardId'],
      message: t.appointment('formValidationErrors.visitorCardId'),
    });
